data:
  augmentation: conservative
  balance_ratio: 0
  channels: (3,)
  data_file: Data/labels_regression_aiahmi.csv
  dim: 128
  feature_cols:
  - flare_rate_y
  - flare_rate_m
  - flare_rate_w
  - max_flare_72h
  - max_flare_48h
  - max_flare_24h
  file_col: filename
  flare_thresh: 1.0e-05
  flux_thresh: 15000000
  forecast_window: 24
  label: high_flux
  maxval: (5,)
  regression: true
  test: ''
  val_split: 0
  zarr_file: /d0/euv/aia/preprocessed/aia_hmi_stacks_2010_2023_1d_1k.zarr
meta:
  id: None
  project: flare-forecast
  resume: false
  user: kierav
model:
  checkpoint_location: null
  dropout_ratio: 0
  load_checkpoint: false
testing:
  eval: false
  savedir: results
  savefile: 24h_aia193
training:
  batch_size: 256
  device: gpu
  epochs: 100
  lr: 0.01
  wd: 0.001
