data:
  augmentation: conservative
  balance_ratio: 0
  channels:
  - 0
  data_file: Data/labels_regression_cleanedandchecked.csv
  dim: 128
  feature_cols:
  - tot_us_flux
  - tot_flux
  - datamin
  - datamax
  - flare_rate_y
  - flare_rate_m
  - flare_rate_w
  - max_flare_72h
  - max_flare_48h
  - max_flare_24h
  file_col: filename
  flare_thresh: 1.0e-05
  flux_thresh: 15000000
  forecast_window: 24
  label: flare
  maxval:
  - 500
  regression: true
  test: 'test_a'
  use_zarr_dataset: false
  val_split: 0
  zarr_file: /d0/euv/aia/preprocessed/aia_hmi_stacks_2010_2023_1d_1k.zarr
meta:
  id: None
  project: flare-forecast-regression
  resume: false
  user: kierav
model:
  checkpoint_location: None
  dropout_ratio: 0
  load_checkpoint: false
testing:
  eval: true
  savedir: results
  savefile: 24h_historical_testa_regression
training:
  batch_size: 256
  device: gpu
  epochs: 100
  lr: 0.0001
  wd: 0.001
