data:
  augmentation: conservative
  balance_ratio: 0
  data_file: Data/labels_all_smoothed.csv
  dim: 128
  feature_cols: ['tot_us_flux','tot_flux','datamin','datamax','flare_rate_y','flare_rate_m','flare_rate_w','max_flare_72h','max_flare_48h','max_flare_24h']
  flare_thresh: 1.0e-05
  flux_thresh: 15000000
  forecast_window: 24
  label: flare
  split_type: temporal
  val_split: 0
meta:
  id: None
  project: flare-forecast
  resume: false
model:
  checkpoint_location: None
  dropout_ratio: 0
  load_checkpoint: false
testing:
  eval: false
training:
  batch_size: 256
  epochs: 100
  lr: 0.0001
  pretrain: false
  wd: 0.001
