# config file for torch lightning

meta: 
  project: 'flare-forecast'
data:
  data_file: 'Data/labels_all_smoothed2.csv'
  forecast_window: 24
  dim: 128
  split_type: 'temporal'
  balance_ratio: 0
  label: 'flare'
  flux_thresh: 15000000
  flare_thresh: 0.00001
  augmentation: None
model:
  dropout_ratio: 0
  load_checkpoint: False
  checkpoint_location: 'kierav/flare-forecast/model-4v7j7rnt:v17'
training:
  lr: 0.0001
  wd: 0.001
  batch_size: 512
  epochs: 100
  
