data:
  augmentation: conservative
  balance_ratio: 0
  data_file: Data/labels_regression_cleanedandchecked.csv
  dim: 128
  feature_cols: []
  file_col: filename
  flare_thresh: 1.0e-05
  flux_thresh: 15000000
  forecast_window: 24
  label: flare
  maxval: 300
  regression: true
  test: ''
  val_split: 0
meta:
  id: None
  project: flare-forecast-regression
  resume: false
  user: kierav
model:
  checkpoint_location:  None
  dropout_ratio: 0
  load_checkpoint: false
testing:
  eval: true
  savefile: '24h_testa'
  savedir: 'results'
training:
  batch_size: 256
  device: gpu
  epochs: 100
  lr: 0.0001
  wd: 0.001
