data:
  data_file: 'Data/labels_all_smoothed2.csv'
  forecast_window: 24
  dim: 128
  split_type: 'temporal'
  val_split: 0
  balance_ratio: 0
  label: 'flare'
  flux_thresh: 15000000
  flare_thresh: 0.00001
  augmentation: None
meta:
  project: flare-forecast
model:
  dropout_ratio: 0
  load_checkpoint: false
  checkpoint_location: kierav/flare-forecast/model-eiwwrygz:v92
training:
  batch_size: 256
  epochs: 100
  lr: 0.0001
  wd: 0.001