data:
  augmentation: None
  balance_ratio: 0
  data_file: Data/labels_all_smoothed2.csv
  dim: 128
  flare_thresh: 1.0e-05
  flux_thresh: 15000000
  forecast_window: 192
  label: flare
  split_type: temporal
  val_split: 0
meta:
  project: flare-forecast
model:
  checkpoint_location: kierav/flare-forecast/model-eiwwrygz:v92
  dropout_ratio: 0
  load_checkpoint: false
training:
  batch_size: 256
  epochs: 100
  lr: 0.0001
  wd: 0.001
