# set up download parameters
email: 'kiera.vds@gmail.com'
start_date: '2011-01-01'
end_date: '2011-01-02'
wavelength: 171
instrument_download: []
instrument_process: ['HMI', 'MDI', '512','SPMG', 'MWO'] 
save_dir: 'Data'   # where to save data
cadence: '1d'      # desired cadence (much less than 1 day may require
format: 'fits'
dlim: 1000
newdir: 'Data/hdf5_smoothed'

# set up labeling parameters
forecast_windows: '12 24 48' #'24''48'


